### ISSUE TITLE
吴青峰个人单曲

### ISSUE THREAD

**Issue by ZhongLingyuxiu1028** [kaluojushi/sodaguide#13]
吴青峰三专前个人单曲：
- 另个时空的你 Another You（官方翻译）

吴青峰三专后个人单曲：
- 我们都拥有海洋 We own All the Ocean（个人翻译）

**Comment by ZhongLingyuxiu1028** [comment]
玠玮和青峰合唱的 《再也不見》官方译名是 You Hurt Me Deeply
> ![image](https://github.com/kaluojushi/sodaguide/assets/42133014/234c4758-bdcf-4669-9c35-9e8c3dcc43e6)
> ![image](https://github.com/kaluojushi/sodaguide/assets/42133014/91ffbcbc-778e-4e9c-b880-428a9f0a10ca)

**Comment by ZhongLingyuxiu1028** [comment]
吴青峰二专前个人单曲：
- 寂寞的時候 When I am Missing You 
> ![image](https://github.com/kaluojushi/sodaguide/assets/42133014/32800d03-06b1-4af6-b33f-dd914a1b16fe)

**Comment by ZhongLingyuxiu1028** [comment]
吴青峰二专前个人单曲：
- 你的影子是我的海 （个人猜测译名是 my shadow my shelter）
> ![image](https://github.com/kaluojushi/sodaguide/assets/42133014/a46d227e-85f8-4872-9ea2-0075fa2f2854)
> ![4e1307e94a6072a465acee895feb6a9](https://github.com/kaluojushi/sodaguide/assets/42133014/83f66f8e-87c2-4742-b1e1-b647cd67795f)

**Comment by kaluojushi** [comment]
感谢！会修改翻译！
（歌曲的英文翻译其实是为了以后方便做域名哈哈哈）

**Comment by ZhongLingyuxiu1028** [comment]
青峰太空备忘记发的窥可能加上20周年版合适点：
- 窥（20周年版）Peeping: 20th Anniversary
> ![image](https://github.com/kaluojushi/sodaguide/assets/42133014/eea92496-be1c-41b4-9c9f-e00866f3bcb4)
